# Logitech Attack3
axis_linear: 1  # Forward/Back
scale_linear: 0.2
scale_linear_turbo: 1.5

axis_angular: 0  # Left/Right
scale_angular: 1.0

enable_button: 0  # Trigger
enable_turbo_button: 1  # Button 2 aka thumb button
